//
// Donation.swift
//
// Auto-generated by GSParseSchema on 12/17/15.
// https://github.com/Grepstar/GSParseSchema
//

import Parse

class Donation : PFObject, PFSubclassing {

	override class func initialize() {
		struct Static {
			static var onceToken : dispatch_once_t = 0;
		}
		dispatch_once(&Static.onceToken) {
			self.registerSubclass()
		}
	}

	class func parseClassName() -> String {
		return "Donation"
	}

	// MARK: Parse Keys

	enum Keys: String {
		case donationCategories = "donationCategories"
		case donor = "donor"
	}

	// MARK: Properties

	@NSManaged var donationCategories: [DonationCategory]?
	@NSManaged var donor: User?
}