//
// DropOffAgency.swift
//
// Auto-generated by GSParseSchema on 12/17/15.
// https://github.com/Grepstar/GSParseSchema
//

import Parse

class DropOffAgency : PFObject, PFSubclassing {

	override class func initialize() {
		struct Static {
			static var onceToken : dispatch_once_t = 0;
		}
		dispatch_once(&Static.onceToken) {
			self.registerSubclass()
		}
	}

	class func parseClassName() -> String {
		return "DropOffAgency"
	}

	// MARK: Parse Keys

	enum Keys: String {
		case agencyName = "agencyName"
		case agencyAddress = "agencyAddress"
		case agencyGeoLocation = "agencyGeoLocation"
	}

	// MARK: Properties

	@NSManaged var agencyName: String?
	@NSManaged var agencyAddress: String?
	@NSManaged var agencyGeoLocation: PFGeoPoint?
}