//
// User.swift
//
// Auto-generated by GSParseSchema on 12/17/15.
// https://github.com/Grepstar/GSParseSchema
//

import Parse

class User : PFUser {

	override class func initialize() {
		struct Static {
			static var onceToken : dispatch_once_t = 0;
		}
		dispatch_once(&Static.onceToken) {
			self.registerSubclass()
		}
	}

	// MARK: Parse Keys

	enum Keys: String {
		case AuthData = "AuthData"
		case profileImage = "profileImage"
		case name = "name"
	}
    
    func phoneNumber() -> String? {
        if let username = username {
            var phoneNumber = username
            if phoneNumber.hasPrefix("+") == false {
                phoneNumber = "+" + phoneNumber
            }
            if Backend.sharedInstance().isValidPhoneNumber(phoneNumber) {
                return phoneNumber
            }
        }
        return nil
    }
    
	// MARK: Properties

	@NSManaged var AuthData: String?
	@NSManaged var profileImage: PFFile?
	@NSManaged var name: String?
}